services:
  monitor-app:
    build: ./
    ports:
      - "3000:3000"
    environment:
      - METRICS_AUTH_TOKEN=asiimov
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus          
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana        
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 

networks:
  monitoring:

volumes:                                      
  prometheus_data:
  grafana_data:
